name: Expression
favicon: null
layout_spectrum: 0
typography_spectrum: 0.57505
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f2f2f2'
    - '#407d99'
    - '#6e9bb0'
    - '#d7e0e4'
    - '#9dbac7'
  brandStrength: 1
  lightness: 0.125
  saturation: 0.9375
  rhythmicContrast: 0.5
purpose: []
