name: Expression
favicon: null
layout_spectrum: 0.9893374119419605
typography_spectrum: 0.8890646463260055
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9039862314239144
  lightness: 0.9398047237191349
  saturation: 0.916212062118575
  rhythmicContrast: 0.32166977250017226
purpose: []
